# FROM node:18-alpine
# 
# WORKDIR /app
# 
# COPY package*.json ./
# RUN npm install
# 
# COPY . .
# 
# RUN npm run build
# 
# EXPOSE 5173
# 
# CMD ["npm", "run", "preview"]

# Hoặc sử dụng Nginx để phục vụ static files
FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
